import PartnerSidebar from "@/app/components/partner/sidebar"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <section className="flex">
      <PartnerSidebar />
      <div className="p-8 text-center justify-center flex-1" id="content">
        {children}
      </div>
    </section>
  )
}