import './globals.css'
import { Inter } from 'next/font/google'
import Nav from '@/app/components/nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const links = [
  { id: 1, title: 'Home', slug: '/' },
  { id: 2, title: 'Admin Dashboard', slug: '/admin' },
  { id: 3, title: 'Partner Login', slug: '/partner' },
]

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav links={links}/>
        {children}
      </body>
    </html>
  )
}
